# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 599a075615c1f7913171cbf36869cb997126d032f096b1b829454075cb937fd0336391d3ece64770825eda21942426d511b408dcd8453db2cf59ef1b393c5d24

test:
  secret_key_base: 464f8f13e8189df609245c3094dfafc2972cf61855c2dc3e1e64b756961c34d61e0972649b02eec82ba1d95782ebae656299c805564fe7ae21dc6b20fdf26c0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
